version: "3"
services:
  stable-diffusion:
    build: ./
    restart: unless-stopped
    container_name: stable-diffusion-webui
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - UID=1000
      - GID=1000
    volumes:
      - ./models:/home/user/stable-diffusion-webui/models/Stable-diffusion
      - ./settings/webui-user.sh:/home/user/stable-diffusion-webui/webui-user.sh
    ports:
      - 7860:7860
      - 7861:7861
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "4.00"
          memory: 16G
        reservations:
          devices:
            - capabilities: [gpu]
