version: "3"
services:
  stable-diffusion:
    image: kestr3l/stable-diffusion-webui:1.2.0
    restart: unless-stopped
    container_name: stable-diffusion-webui
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - UID=1000
      - GID=1000
      - DIR_GRADIO_AUTH=/run/secrets/gradio_auth
      # Get UID and GID using following commands:
      #   For UID: echo $(id -u)
      #   For GID: echo $(id -g)
    volumes:
      - ./models:/home/user/stable-diffusion-webui/models/Stable-diffusion
      - ./settings/webui-user.sh:/home/user/stable-diffusion-webui/webui-user.sh
    ports:
      - 7860:7860
      - 7861:7861
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "4.00"
          memory: 16G
